# Generated by Django 5.0.3 on 2024-04-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendor_management", "0002_alter_purchaseorder_acknowledgment_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="response_time",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
